name: build Puredarwin
on: [push]

jobs:
  build:
    steps:
    - uses: actions/checkout@v4
    - name: install deps
      run: brew install openssl ninja
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja -DKERNEL_BUILD_XNU=1
