name: build Puredarwin
on: [push]

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: | 
        brew install openssl ninja
        cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja -DKERNEL_BUILD_XNU=1
        ninja -C build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.5
      with:
        path: ./build
